service:
  name: instagram

plugins:
  - serverless-plugin-optimize
  - serverless-offline

# custom:
  # secrets: ${file(./secrets.yml):${self:provider.stage}}

provider:
  name: aws
  runtime: nodejs12.x
#   environment:
#      API_KEY_EXAMPLE: ${self:custom.secrets.API_KEY_EXAMPLE}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: any
          path: /{any+}